### ISSUE TITLE
Unable to run/build on windows 11

### ISSUE THREAD

**Issue by repraze** [sstallion/go-hid#10]
When running on windows 11, I am unable to use the module with `go build ./` output:

```
> go build ./             
# github.com/sstallion/go-hid
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:11:8: undefined: BusUnknown
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:12:8: undefined: BusUSB
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:13:8: undefined: BusBluetooth
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:14:8: undefined: BusI2C
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:15:8: undefined: BusSPI
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:22:9: undefined: BusType
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:23:19: undefined: BusType
```

Steps:
- create a new directory
- `go mod init example`
- `go get github.com/sstallion/go-hid`
- copy `example_test.go` from this repo into `example.go`
- rename `package hid_test` to `package main`
- `go build ./`

I haven't done any installation with hidapi, unaware if I'm missing a step.

**Comment by repraze** [comment]
I tried downloading the latest hidapi release, not sure how to link it

**Comment by sstallion** [comment]
Hi @repraze I was able to follow your steps without issue. CI/CD jobs run against Windows Server 2022, which should behave similarly to Windows 11. The error you posted above is interesting as it indicates that hid.go is not being built for some reason. It might be worth double checking the modcache, worst case you can clean it by issuing `go clean -modcache` and try calling `go get` again.

**Comment by sstallion** [comment]
Almost forgot! There's no need to download HIDAPI separately. The sources are baked into the `hid` package for you already, all you need to do is import the package from your sources.

**Comment by repraze** [comment]
No luck still.

Windows 11 pro
AMD ryzen 7800x3d (not sure if there's limitation there for x86)

``` mod
#go.mod
module hid_test

go 1.20

require github.com/sstallion/go-hid v0.14.1

require golang.org/x/sys v0.11.0 // indirect
```

``` log
PS > go clean -modcache
PS > go get
go: downloading github.com/sstallion/go-hid v0.14.1
go: downloading golang.org/x/sys v0.11.0
PS > go run .
# github.com/sstallion/go-hid
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:11:8: undefined: BusUnknown
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:12:8: undefined: BusUSB
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:13:8: undefined: BusBluetooth
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:14:8: undefined: BusI2C
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:15:8: undefined: BusSPI
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:22:9: undefined: BusType
..\..\go\pkg\mod\github.com\sstallion\go-hid@v0.14.1\bustype_string.go:23:19: undefined: BusType
```

What I notice in VScode is even after install, the hid references are not found.

![image](https://github.com/sstallion/go-hid/assets/4272467/a6fdac35-1057-444a-9ceb-748f1178e8f5)

`hid.Init()` & `hid.OpenFirst()` return `undefined: hid.Initcompiler[UndeclaredImportedName]`
(https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)

Is there a possibility that the architecture is no detected correctly / dependencies not build so the references aren't found? I've used other packages with C dependencies without issues.

**Comment by sstallion** [comment]
Hmm. hid.go is architecture independent - it looks like there might be an
issue with your environment. Do you have any environment variables defined
that could be affecting go? Are you able to pull in other packages and use
them?

**Comment by repraze** [comment]
The PC is less then a week old.
I am able to use https://github.com/getlantern/systray.

Interestingly, when I open hid, it says it's not included in my project.

![image](https://github.com/sstallion/go-hid/assets/4272467/3e29c006-d19d-4a21-a77b-f9caa87a2f5b)


```
This file is within module "..\\..\\go\\pkg\\mod\\github.com\\sstallion\\go-hid@v0.14.1", which is not included in your workspace.
To fix this problem, you can add a go.work file that uses this directory.
See the documentation for more information on setting up your workspace:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.go list
```

Only `bustype_string.go` seems to be included (no warning on `package hid`)
All other `.go` files have the warning.

Might be linked to the `import "C"`

**Comment by sstallion** [comment]
It looks like you have `CGO_ENABLED` set to `0`. In order to use package `hid`, you'll need to enable Cgo as it is needed to interface with HIDAPI. Try enabling this and rebuilding, I think you should start seeing correct behavior.

**Comment by repraze** [comment]
Got it compiling.

`CGO_ENABLED=1` will enable compilation. For windows, you won't be able to compile without a proper gcc setup.

My steps for cross compilation
 - WSL with ubuntu installed
 - installed go in WSL by wget the latest .tar.gz from https://go.dev/dl/
   - move the files in `/usr/local`
   - add `export PATH=$PATH:/usr/local/go/bin` to `.bashrc`
 - installed mingw32 from cross compile with `sudo apt-get install gcc-mingw-w64`
 - can now cross compile/run from WSL for windows with `CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go run .`
 
 You can also build, copy `.exe` other to windows and run.
 
 CGO isn't available out of the box in windows unfortunatly.

**Comment by sstallion** [comment]
Cgo can be something of a pain on Windows. All you need is a compatible GCC toolchain. There are a few writeups online on how to do it natively, but I've found the following to be the most helpful using MSYS2: https://github.com/faiface/pixel/wiki/Building-Pixel-on-Windows

I'm glad you were able to get everything working!

**Comment by repraze** [comment]
Thanks for the help - this is good for future reference.

**Comment by dobrikov91** [comment]
@sstallion, could you add "CGO_ENABLED=1" and gcc requirements to the installation guide?
Fresh windows golang installation has nno cgo support and it's quiet tricky to find this thread.

**Comment by sstallion** [comment]
> @sstallion, could you add "CGO_ENABLED=1" and gcc requirements to the installation guide? Fresh windows golang installation has nno cgo support and it's quiet tricky to find this thread.

Sure thing! I'm currently traveling, but I should be able to get to this in the next few days.

**Comment by Xelus22** [comment]
hey, i know this is abit of a necro, but did u ever get this to run in WSL2 itself? 
I followed your steps to get this working and running in Windows, but I can't get it to run any in WSL2... :(
