### ISSUE TITLE
Statically build does not work on linux

### ISSUE THREAD

**Issue by db-tech** [sstallion/go-hid#2]
Hi,

I tried to get this static build to work, but I only get the error "no such path or directory" when I do make all.

I guess this is because the vendor directory is not downloaded by the "go get" command. probably because this command does only work with modules nowadays ?

If you could give me a hint how to get this to work statically, that would be awesome.

**Comment by sstallion** [comment]
Hi @db-tech, I apologize for the long delay (I wasn't receiving email notifications for some reason). I've just pushed updates to properly support Go modules - give that a shot and see if that takes care of the issue you were seeing.

**Comment by db-tech** [comment]
hi @sstallion, thanks for the response. I will test it, but it might take some time because I am currently working on something else. After christmas, i will get back to it and report the results

**Comment by sstallion** [comment]
No worries! As a heads up, I'm working through updating HIDAPI to the
latest release (0.12.0) of the libusb/hidapi fork to pick up some bug fixes
on other OSes. I should have this finished up later today if all goes well!

**Comment by sstallion** [comment]
Hey @db-tech. I've done a bit of work over the last couple of weeks updating how go-hid is built and used. Static linking is now the only method of using HIDAPI and CI has been updated as well to verify behavior on FreeBSD, Linux, macOS, and Windows. I'm feeling confident this issue has been resolved, so I'll close it for now. Please let me know if you run into any problems in the future!

**Comment by umbynos** [comment]
Hello @sstallion, sorry to post on a closed issue.
I've tried to statically building by `CGO_ENABLED=0 go build` but this is what I get:
```
./hid.go:32:16: undefined: hid.Open
```

With a simple `go build` everything works as expected, but the binary is not static: `ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a8f93908ccb5081d424cfe3dfa362eec83e84158, for GNU/Linux 3.2.0, with debug_info, not stripped`

Of course, I installed the [prerequisites](https://github.com/libusb/hidapi/blob/master/BUILD.md#linux).
