### ISSUE TITLE
[feature request] add ability to dettach and reattach kernel driver.

### ISSUE THREAD

**Issue by bokunodev** [sstallion/go-hid#4]
add ability to dettach and reattach kernel driver.

**Comment by sstallion** [comment]
@bokunodev This seems a little out of scope for a set of portable language bindings. Could you describe in a little more detail what you would like to see?

**Comment by sstallion** [comment]
@bokunodev This may be supported already. I took a quick look through `hidapi_libusb.c` this evening and it looks like on non-FreeBSD hosts (ie. Linux), the kernel driver should be detached on `hid_open` and reattached on `hid_close` by default.

Have you tried building the package with libusb support enabled? By default, hidraw is assumed but you can enable libusb support by building with the following tag:

    $ go build -tags libusb ./...

**Comment by sstallion** [comment]
Any time, and thanks!
