### ISSUE TITLE
Writes not being received by USB device on Mac OS 

### ISSUE THREAD

**Issue by nulltrope** [sstallion/go-hid#5]
I'm using `go-hid` to send "raw" HID bytes back and forth between an Adafruit RP2040 Macropad. On Windows 11, this works flawlessly however for some reason on Mac OS (Monterey 12.6.6) I can read data just fine but when I write data, it never gets seen by my device. Strangely, I get no errors from calling `device.Write()` and it returns a positive int as if it did send the correct number of bytes. I've also tried including and excluding the "report ID" byte in my write call, and it had no effect.

I _think_ this is relating to `go-hid` and not an issue with the macropad/usb device itself, because I tried writing to the device on Mac using https://github.com/todbot/hidapitester and it works just fine. 

Here is my USB device descriptor: 
```
RAWHID_REPORT_DESCRIPTOR = bytes((
    0x06, 0x00, 0xFF,  # Usage Page (Vendor Defined 0xFF00)
    0x09, 0x01,        # Usage (0x01)
    0xA1, 0x01,        # Collection (Application)
    0x09, 0x02,        #   Usage (0x02)
    0x15, 0x00,        #   Logical Minimum (0)
    0x26, 0xFF, 0x00,  #   Logical Maximum (255)
    0x75, 0x08,        #   Report Size (8)
    0x95, 0x40,        #   Report Count (64)
    0x81, 0x02,        #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
    0x09, 0x03,        #   Usage (0x03)
    0x15, 0x00,        #   Logical Minimum (0)
    0x26, 0xFF, 0x00,  #   Logical Maximum (255)
    0x75, 0x08,        #   Report Size (8)
    0x95, 0x40,        #   Report Count (64)
    0x91, 0x02,        #   Output (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
    0xC0,              # End Collection
))
```

And here's the hidapitester command that works fine:
```
./hidapitester --vidpid 239A/8108 -l 64 --open --send-output 1234
```

Do you have any ideas/further troubleshooting I can try? I'm a bit at a loss! Thanks.

**Comment by sstallion** [comment]
Hi @nulltrope! Is there any chance you have access to a protocol analyzer like a Beagle USB 12 or 480? I'm curious if there's a difference in payloads being generated by `hidaptester` versus `go-hid`. It might also be helpful to post the source that you're having issues with.

**Comment by nulltrope** [comment]
Ah this was totally my fault, I realized I wasn't padding the output to be the proper length expected by the device descriptor. For some reason this worked on windows but maybe Mac's hid implementation is more strict. Anyways it works now when I pad my byte slice with extra 0's to make it equivalent to the length my descriptor expects. Thanks for getting back anyways.

**Comment by sstallion** [comment]
> Thanks for getting back anyways.

No worries, I'm glad everything is working for you!
