### ISSUE TITLE
Undefined variables from bustype_string.go

### ISSUE THREAD

**Issue by chuongle** [sstallion/go-hid#8]
I tried to build the example code on a Raspbian OS, Ubuntu and MacOS. The only one I got working is the Raspbian OS. I kept receiving these following errors on the other OS:
```
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:11:8: undefined: BusUnknown
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:12:8: undefined: BusUSB
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:13:8: undefined: BusBluetooth
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:14:8: undefined: BusI2C
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:15:8: undefined: BusSPI
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:22:9: undefined: BusType
../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:23:19: undefined: BusType
```

I understand it could fail on MacOS but I don't know why it would also fail on Ubuntu. I made sure to install all the necessary depenedencies for libusb. Can someone please help me understand why this failed?

**Comment by sstallion** [comment]
Hi @chuongle, could you please provide some additional information on which OS and Golang versions you were using along with the commands used to build the package?

**Comment by chuongle** [comment]
@sstallion I apologize I should add more info regarding this. Let's take MacOS out of the picture.

**Ubuntu**
OS Version: `Ubuntu 18.04.6 LTS`
Go Version: `go version go1.20.6 linux/amd64`

**Raspbian OS**
OS Version: `Buster`
Go Version: `go version go1.20.6 linux/arm`

For additional information, I have 2 small applications setup to test with the folder structure like this:

```
.
└── Developments/
    ├── application-A/
    │   └── example.go (follow the example_test.go)
    └── application-B/
        ├── build.sh
        └── commands/
            ├── command1/
            │   └── run.go
            └── command2/
                └── run2.go
```

For the `applicationA` I tried these 2 commands. Both of them works and I had no issue.
```
- go build -tags libusb ./
- go run -tags libusb ./
```

For my `applicationB` I basically has the script to run that go build command but I had the additional `-trimpath` flag. 

I just found out right before you replied back to my issue that: if I ran the go build command directly I won't have any issue. But if I ran my script, I would basically encounter that error above (with or without the `-trimpath` flag). I guess this is not related to the package so we can close the issue. But if you have any advice, I would love to hear!

**Comment by sstallion** [comment]
No worries! From the error message, it looks like dependencies may not be resolving correctly using `build.sh`. Are you using modules with your applications? If not, I'd suggest giving that a shot since that can make working with dependencies easier.

**Comment by chuongle** [comment]
@sstallion sorry to bring this up again. I was busy and did not have time to get back until now. I debug some more on this and it looks like the issue is with cross compiling. If i am on a arm linux base, I won't have any issue. But if I am on ubuntu and try to compile for arm, I will encounter the issue above. Do you have any advice for me? I saw another [issue](https://github.com/sstallion/go-hid/issues/10) having somewhat similar issue. But it's for window instead of linux

**Comment by sstallion** [comment]
@chuongle No worries, I apologize for taking so long before responding. Could you give me a little more information? Are you using the latest release? Are you using Go Modules? What command are you using to cross-compile your application?

**Comment by chuongle** [comment]
@sstallion Thank you for getting back!

I am using the latest release `v0.14.1` and I do use Go modules structure. Here is the structure of my application

```
.
└── application/
    ├── go.mod
    ├── go.sum
    ├── script/
    │   └── build.sh
    └── cmd/
        ├── command1/
           └── main.go
```

In my `build.sh`, i had this command:

```
GOOS=linux GOARCH=arm GOARM=5 go build -tags libusb -trimpath -ldflags "${SOME_FLAGS}" "./cmd/command1"
```

Regardless of running the script or running this command directly, I encountered the same error. I had no issue running this on a raspberry pi. But if I ran it on a Mac or Ubuntu, I will encounter the cross compiling errors:

```
# github.com/sstallion/go-hid
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:11:8: undefined: BusUnknown
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:12:8: undefined: BusUSB
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:13:8: undefined: BusBluetooth
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:14:8: undefined: BusI2C
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:15:8: undefined: BusSPI
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:22:9: undefined: BusType
../../../go/pkg/mod/github.com/sstallion/go-hid@v0.14.1/bustype_string.go:23:19: undefined: BusType
```
